sudo: required
services:
  - docker

before-install:
  - docker build -t saratkota/react_docker_aws -f Dockerfile.dev .

script:
  - docker run -e CI=true saratkota/react_docker_aws npm test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env-2"
  bucket_name: "elasticbeanstalk-ap-south-1-671959627236"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
